const produtos =[
    {
        nome:"Banana",
        preco:9.99,
        categoria:"frutas",
        image:"cl,çc",
        imgDescricao:""
    },
    {
        nome:"Melancia",
        preco:9.99,
        categoria:"frutas",
        image:"cl,çc",
        imgDescricao:""
    },
    {
        nome:"Uva",
        preco:9.99,
        categoria:"frutas",
        image:"cl,çc",
        imgDescricao:""
    },
    {
        nome:"Coca-cola",
        preco:9.99,
        categoria:"bebidas",
        image:"cl,çc",
        imgDescricao:""
    },
    {
        nome:"Suco",
        preco:9.99,
        categoria:"bebidas",
        image:"cl,çc",
        imgDescricao:""
    },
    {
        nome:"Cerveja",
        preco:9.99,
        categoria:"bebidas",
        image:"cl,çc",
        imgDescricao:""
    },
    {
        nome:"Sabão",
        preco:9.99,
        categoria:"Higiene",
        image:"cl,çc",
        imgDescricao:""
    },
    {
        nome:"Detergente",
        preco:9.99,
        categoria:"higiene",
        image:"cl,çc",
        imgDescricao:""
    },
    {
        nome:"Sabonete",
        preco:9.99,
        categoria:"higiene",
        image:"cl,çc",
        imgDescricao:""
    },
]